os: Windows

language: 
    - python
    - java
    
python:
  - "3.6"
# command to install dependencies
install:
   - gradle assemble
# command to run tests
script:
  - gradle check

# command to run tests
script:
  - pytest
  - flake8
