language:
   - python
python:
   - "3.6"
services:
   - docker

before_install:
  - docker build -t recognitron .
  # command to install dependencies
install:
   - pip install -r requirements.txt
   - pip install pylint_runner
   - pip install flake8
   - gradle assemble
  # command to run tests
script:
  - pytest
  - flake8
  - docker run -d -p 4000:80 recognitron

