jobs:
  include:
      - stage: test
        language: python
        python:
        - "3.6"
        services:
        - docker

        before_install:
        - docker build -t recognitron .
        # command to install dependencies
        install:
        - pip install -r requirements.txt
        - pip install pylint_runner
        # - pip install flake8
            # command to run tests
        script:
        - pytest
        # - flake8
        - docker run -d -p 4000:80 recognitron

      - stage: test
        language: android
        jdk: oraclejdk8
        android:
        components:
            #- tools
            #- platform-tools
            #- build-tools-28.0.3
            #- android-28
            #- extra
        services:
        - docker

        addons:
            apt:
                packages:
                - docker-ce

        before_install:
        - cd client
        - docker build -q -t fruit-recognizer-app .

        script:
        - docker run --rm --mount type=bind,source="$(pwd)/..",target=/app fruit-recognizer-app ./gradlew clean build check


