os: Windows

language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint_runner
  - pip install flake8

# command to run tests
script:
  - pytest

# command to run tests
script:
  - pytest
  - flake8

language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra

script:
    - "./gradlew clean build test lint"
