os: Windows

language: 
    - python
    - java
    - android
python:
  - "3.6"
services:
 - docker

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint_runner
  - pip install flake8
  - gradle assemble
  - docker build -t recognitron .

services:
  - docker

before_install:
  - docker build -t recognitron .
  - docker run -p 4000:80 recognitron

# command to run tests
script:
  - pytest
  - flake8
  - gradle check
  - "./gradlew clean build test lint"

jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra

